[env:teensy41]
platform = teensy
board = teensy41
upload_protocol = teensy-cli
framework = arduino
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wno-unused-parameter
lib_deps =
lib_extra_dirs = lib

